
# See https://github.com/subosito/flutter-action

name:  JRPN15 Build
run-name: ${{ github.actor }} JRPN15 Build
on: 
    workflow_dispatch:          # Manually

    # push:
    #     branches: [master]
    #     paths-ignore:
    #         - '**/README.md'

jobs:
    macos-build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - uses: subosito/flutter-action@v2
              with:
                  channel: 'stable'
                  architecture: x64
                  # flutter:version: '3.0.0'
            - run: flutter pub get
            - run: flutter config --enable-macos-desktop
            - run: flutter config --enable-ios
            - run: flutter build ipa --no-codesign --analyze-size --code-size-directory analysis
            - run: cd build/ios/archive/Runner.xcarchive/Products/Applications ; zip -r --symlinks jrpn15_ios.app.zip Runner.app
            - uses: actions/upload-artifact@v3
              with:
                name: analysis
                path: analysis
            - uses: actions/upload-artifact@v3
              with:
                name:  jrpn15_ios
                path:  build/ios/archive/Runner.xcarchive/Products/Applications/jrpn15_ios.app.zip

